"""Disease profiles for procedural scenario generation.

Provides disease-specific differential expression patterns,
pathway enrichments, markers, mechanisms, and responding cell types.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple


@dataclass
class DiseaseProfile:
    name: str
    display_name: str
    tissue: str
    condition_name: str
    de_genes: Dict[str, Tuple[float, float]]
    pathways: Dict[str, Tuple[float, float]]
    markers: List[str]
    mechanism_templates: List[str]
    responding_cell_types: List[str] = field(default_factory=list)
    hidden_failure_templates: List[str] = field(default_factory=list)


DISEASE_PROFILES: Dict[str, DiseaseProfile] = {
    "dilated_cardiomyopathy": DiseaseProfile(
        name="dilated_cardiomyopathy",
        display_name="dilated cardiomyopathy",
        tissue="heart",
        condition_name="dilated_cardiomyopathy",
        de_genes={
            "NPPA": (1.8, 3.5),
            "NPPB": (2.0, 4.0),
            "MYH7": (1.0, 2.5),
            "COL1A1": (1.0, 2.2),
            "COL3A1": (0.8, 1.8),
            "POSTN": (1.5, 3.0),
            "CCL2": (0.8, 1.8),
            "IL6": (0.5, 1.5),
            "TGFB1": (0.7, 1.6),
            "ANKRD1": (1.5, 3.0),
            "XIRP2": (-2.0, -0.8),
            "MYL2": (-1.5, -0.5),
        },
        pathways={
            "cardiac_muscle_contraction": (0.3, 0.6),
            "extracellular_matrix_organisation": (0.7, 0.95),
            "inflammatory_response": (0.5, 0.8),
            "TGF_beta_signalling": (0.6, 0.85),
            "apoptosis": (0.4, 0.65),
        },
        markers=["NPPA", "NPPB", "POSTN", "COL1A1"],
        mechanism_templates=[
            "TGF-beta-driven fibrosis",
            "inflammatory macrophage infiltration",
        ],
        responding_cell_types=["cardiac_fibroblast", "macrophage"],
    ),
    "Alzheimer": DiseaseProfile(
        name="Alzheimer",
        display_name="Alzheimer's disease",
        tissue="brain",
        condition_name="Alzheimer",
        de_genes={
            "TREM2": (1.0, 2.5),
            "APOE": (1.2, 2.8),
            "CLU": (0.8, 2.0),
            "C1QA": (1.0, 2.2),
            "C1QB": (0.9, 2.0),
            "GFAP": (1.5, 3.0),
            "AQP4": (0.6, 1.5),
            "SLC17A7": (-1.5, -0.5),
            "NRGN": (-2.0, -0.8),
            "SNAP25": (-1.2, -0.4),
        },
        pathways={
            "complement_cascade": (0.7, 0.9),
            "neuroinflammation": (0.65, 0.85),
            "amyloid_processing": (0.6, 0.8),
            "synaptic_signalling": (0.3, 0.5),
            "lipid_metabolism": (0.5, 0.7),
        },
        markers=["TREM2", "APOE", "GFAP", "C1QA"],
        mechanism_templates=[
            "TREM2-mediated microglial activation in amyloid clearance",
            "complement-driven synaptic pruning",
            "reactive astrogliosis amplifying neuroinflammation",
        ],
        responding_cell_types=["microglia", "astrocyte"],
    ),
    "colorectal_cancer": DiseaseProfile(
        name="colorectal_cancer",
        display_name="colorectal cancer",
        tissue="colon",
        condition_name="colorectal_cancer",
        de_genes={
            "MYC": (1.5, 3.0),
            "KRAS": (0.8, 1.8),
            "TP53": (-1.5, -0.5),
            "APC": (-1.8, -0.8),
            "CDH1": (-1.2, -0.4),
            "VIM": (1.0, 2.5),
            "MKI67": (1.5, 3.0),
            "CD44": (1.0, 2.2),
            "LGR5": (0.8, 2.0),
        },
        pathways={
            "Wnt_signalling": (0.75, 0.95),
            "cell_cycle": (0.7, 0.9),
            "EMT": (0.6, 0.85),
            "p53_signalling": (0.3, 0.5),
            "MAPK_signalling": (0.55, 0.75),
        },
        markers=["MYC", "CD44", "VIM", "MKI67"],
        mechanism_templates=[
            "Wnt/beta-catenin-driven tumour stem cell expansion",
            "epithelial-mesenchymal transition promoting invasion",
        ],
        responding_cell_types=["stem_cell", "macrophage", "fibroblast"],
    ),
    "type2_diabetes": DiseaseProfile(
        name="type2_diabetes",
        display_name="type 2 diabetes",
        tissue="pancreas",
        condition_name="type2_diabetes",
        de_genes={
            "INS": (-2.0, -0.8),
            "MAFA": (-1.5, -0.5),
            "PDX1": (-1.2, -0.4),
            "UCN3": (-1.8, -0.6),
            "GCG": (0.8, 2.0),
            "ARX": (0.5, 1.5),
            "IAPP": (0.6, 1.8),
            "TXNIP": (1.0, 2.5),
            "DDIT3": (0.8, 2.0),
        },
        pathways={
            "insulin_signalling": (0.3, 0.5),
            "ER_stress_response": (0.7, 0.9),
            "oxidative_stress": (0.6, 0.8),
            "glucagon_signalling": (0.6, 0.8),
            "apoptosis": (0.5, 0.7),
        },
        markers=["INS", "TXNIP", "IAPP", "DDIT3"],
        mechanism_templates=[
            "ER stress-induced beta cell apoptosis",
            "glucotoxicity-driven beta cell dedifferentiation",
        ],
        responding_cell_types=["beta_cell", "stellate"],
    ),
    "AML": DiseaseProfile(
        name="AML",
        display_name="acute myeloid leukemia",
        tissue="bone_marrow",
        condition_name="AML",
        de_genes={
            "FLT3": (1.5, 3.0),
            "NPM1": (0.8, 2.0),
            "IDH2": (0.6, 1.5),
            "RUNX1": (-1.5, -0.5),
            "CEBPA": (-1.2, -0.4),
            "KIT": (1.0, 2.5),
            "WT1": (1.2, 2.8),
            "MYC": (0.8, 2.0),
        },
        pathways={
            "hematopoietic_cell_lineage": (0.3, 0.5),
            "MAPK_signalling": (0.7, 0.9),
            "PI3K_AKT_signalling": (0.65, 0.85),
            "cell_cycle": (0.7, 0.9),
            "apoptosis": (0.3, 0.5),
        },
        markers=["FLT3", "NPM1", "WT1", "KIT"],
        mechanism_templates=[
            "FLT3-ITD-driven proliferative advantage",
            "myeloid differentiation block via RUNX1 loss",
        ],
        responding_cell_types=["HSC", "GMP"],
    ),
    "rheumatoid_arthritis": DiseaseProfile(
        name="rheumatoid_arthritis",
        display_name="rheumatoid arthritis",
        tissue="synovium",
        condition_name="rheumatoid_arthritis",
        de_genes={
            "IFNG": (1.0, 2.5),
            "TBX21": (0.8, 1.8),
            "IL17A": (1.0, 2.2),
            "RORC": (0.6, 1.5),
            "TNF": (1.2, 2.5),
            "IL6": (1.0, 2.2),
            "MMP3": (1.5, 3.0),
            "MMP1": (1.2, 2.5),
            "CXCL13": (1.0, 2.5),
        },
        pathways={
            "JAK_STAT_signalling": (0.7, 0.9),
            "TNF_signalling": (0.7, 0.9),
            "Th17_differentiation": (0.6, 0.8),
            "NF_kB_signalling": (0.65, 0.85),
            "matrix_metalloproteinase_activity": (0.7, 0.9),
        },
        markers=["TNF", "IL6", "MMP3", "CXCL13"],
        mechanism_templates=[
            "TNF/NF-kB-driven synovial inflammation",
            "Th17-mediated cartilage destruction via MMPs",
        ],
        responding_cell_types=["fibroblast", "macrophage", "CD4_T_cell"],
    ),
    "hepatocellular_carcinoma": DiseaseProfile(
        name="hepatocellular_carcinoma",
        display_name="hepatocellular carcinoma",
        tissue="liver",
        condition_name="HCC",
        de_genes={
            "GPC3": (2.0, 4.0),
            "AFP": (1.5, 3.5),
            "EPCAM": (1.0, 2.5),
            "MYC": (1.0, 2.5),
            "VEGFA": (1.2, 2.8),
            "MKI67": (1.5, 3.0),
            "ALB": (-2.0, -0.8),
            "CYP3A4": (-1.8, -0.6),
            "APOB": (-1.5, -0.5),
        },
        pathways={
            "Wnt_signalling": (0.7, 0.9),
            "cell_cycle": (0.75, 0.95),
            "angiogenesis": (0.6, 0.8),
            "PI3K_AKT_signalling": (0.65, 0.85),
            "p53_signalling": (0.3, 0.5),
        },
        markers=["GPC3", "AFP", "VEGFA", "MKI67"],
        mechanism_templates=[
            "Wnt/beta-catenin-driven hepatocyte dedifferentiation",
            "VEGF-mediated tumour angiogenesis",
        ],
        responding_cell_types=["kupffer_cell", "stellate_cell"],
        hidden_failure_templates=[
            "Tumour heterogeneity may confound DE in mixed biopsies",
        ],
    ),
    "atherosclerosis": DiseaseProfile(
        name="atherosclerosis",
        display_name="atherosclerosis",
        tissue="aorta",
        condition_name="atherosclerosis",
        de_genes={
            "TREM2": (1.5, 3.0),
            "CD9": (1.0, 2.2),
            "LGALS3": (1.2, 2.5),
            "APOE": (0.8, 2.0),
            "MMP9": (1.0, 2.5),
            "IL1B": (0.8, 2.0),
            "ACTA2": (-1.5, -0.5),
            "MYH11": (-2.0, -0.8),
            "CNN1": (-1.5, -0.5),
        },
        pathways={
            "lipid_metabolism": (0.7, 0.9),
            "inflammatory_response": (0.65, 0.85),
            "foam_cell_formation": (0.7, 0.9),
            "smooth_muscle_contraction": (0.3, 0.5),
            "complement_cascade": (0.5, 0.7),
        },
        markers=["TREM2", "LGALS3", "MMP9", "CD9"],
        mechanism_templates=[
            "TREM2+ macrophage-driven foam cell formation",
            "smooth muscle cell phenotypic switching in plaque",
        ],
        responding_cell_types=["macrophage", "smooth_muscle"],
    ),
    "breast_cancer": DiseaseProfile(
        name="breast_cancer",
        display_name="breast cancer",
        tissue="breast",
        condition_name="breast_cancer",
        de_genes={
            "ERBB2": (1.5, 3.5),
            "ESR1": (-1.5, 1.5),
            "MKI67": (1.5, 3.0),
            "MYC": (1.0, 2.5),
            "CDH1": (-1.5, -0.3),
            "VIM": (0.8, 2.2),
            "CD274": (0.8, 2.0),
            "FOXP3": (0.6, 1.5),
            "GZMB": (0.8, 2.0),
        },
        pathways={
            "cell_cycle": (0.7, 0.9),
            "PI3K_AKT_signalling": (0.65, 0.85),
            "EMT": (0.55, 0.8),
            "immune_checkpoint": (0.5, 0.75),
            "estrogen_signalling": (0.3, 0.7),
        },
        markers=["ERBB2", "MKI67", "CD274", "VIM"],
        mechanism_templates=[
            "ERBB2-driven proliferative signalling",
            "immune evasion via PD-L1 upregulation",
        ],
        responding_cell_types=["macrophage", "T_cell", "fibroblast"],
    ),
    "multiple_sclerosis": DiseaseProfile(
        name="multiple_sclerosis",
        display_name="multiple sclerosis",
        tissue="brain",
        condition_name="multiple_sclerosis",
        de_genes={
            "CD68": (1.0, 2.5),
            "CXCL10": (1.2, 2.8),
            "STAT1": (0.8, 2.0),
            "IRF1": (0.8, 1.8),
            "MBP": (-2.0, -0.8),
            "PLP1": (-1.8, -0.6),
            "MOG": (-1.5, -0.5),
            "GFAP": (1.0, 2.5),
            "C3": (0.8, 2.0),
        },
        pathways={
            "interferon_signalling": (0.7, 0.9),
            "neuroinflammation": (0.7, 0.9),
            "complement_cascade": (0.6, 0.8),
            "myelination": (0.2, 0.4),
            "T_cell_activation": (0.6, 0.8),
        },
        markers=["CXCL10", "STAT1", "GFAP", "C3"],
        mechanism_templates=[
            "interferon-driven microglial activation in demyelination",
            "complement-mediated oligodendrocyte damage",
        ],
        responding_cell_types=["microglia", "astrocyte"],
    ),
    "diabetic_nephropathy": DiseaseProfile(
        name="diabetic_nephropathy",
        display_name="diabetic nephropathy",
        tissue="kidney",
        condition_name="diabetic_nephropathy",
        de_genes={
            "HAVCR1": (1.5, 3.0),
            "LCN2": (1.2, 2.8),
            "COL4A1": (1.0, 2.5),
            "VEGFA": (0.8, 2.0),
            "NPHS1": (-1.8, -0.6),
            "NPHS2": (-1.5, -0.5),
            "WT1": (-1.2, -0.4),
            "TGFB1": (1.0, 2.2),
            "FN1": (1.2, 2.5),
        },
        pathways={
            "TGF_beta_signalling": (0.7, 0.9),
            "extracellular_matrix_organisation": (0.7, 0.9),
            "oxidative_stress": (0.6, 0.8),
            "VEGF_signalling": (0.5, 0.7),
            "apoptosis": (0.5, 0.7),
        },
        markers=["HAVCR1", "LCN2", "TGFB1", "FN1"],
        mechanism_templates=[
            "TGF-beta-driven glomerular fibrosis",
            "podocyte loss via oxidative stress",
        ],
        responding_cell_types=["fibroblast", "macrophage"],
    ),
    "melanoma": DiseaseProfile(
        name="melanoma",
        display_name="melanoma",
        tissue="skin",
        condition_name="melanoma",
        de_genes={
            "MLANA": (1.5, 3.0),
            "PMEL": (1.2, 2.5),
            "SOX10": (1.0, 2.2),
            "MKI67": (1.5, 3.0),
            "CD274": (0.8, 2.0),
            "PDCD1": (0.8, 2.0),
            "GZMB": (0.8, 2.0),
            "HAVCR2": (0.6, 1.5),
            "LAG3": (0.6, 1.5),
        },
        pathways={
            "MAPK_signalling": (0.7, 0.9),
            "immune_checkpoint": (0.6, 0.85),
            "cell_cycle": (0.7, 0.9),
            "melanogenesis": (0.5, 0.7),
            "T_cell_exhaustion": (0.55, 0.8),
        },
        markers=["MLANA", "CD274", "GZMB", "MKI67"],
        mechanism_templates=[
            "MAPK-driven melanocyte proliferation",
            "T cell exhaustion via immune checkpoint upregulation",
        ],
        responding_cell_types=["T_cell", "macrophage"],
    ),
}
