"""FastAPI application for the DryLabSim environment."""

from __future__ import annotations

import asyncio
import os
from dataclasses import dataclass
from typing import Any, Dict, Optional
from uuid import uuid4

from fastapi import Body, FastAPI, HTTPException, Query, status
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, ConfigDict, Field, ValidationError

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required for the web interface. Install dependencies with 'uv sync'"
    ) from e

try:
    from ..models import ExperimentAction, ExperimentObservation
    from .demo_ui import register_demo_ui
    from .drylabsim_environment import BioExperimentEnvironment
except ImportError:  # pragma: no cover - direct module import path
    from models import ExperimentAction, ExperimentObservation
    from server.demo_ui import register_demo_ui
    from server.drylabsim_environment import BioExperimentEnvironment


@dataclass
class SessionRecord:
    env: BioExperimentEnvironment
    lock: asyncio.Lock


class SessionResetRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    seed: Optional[int] = Field(default=None, ge=0)
    task_name: Optional[str] = None
    scenario_name: Optional[str] = None
    domain_randomise: Optional[bool] = None


class SessionStepRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    session_id: str
    action: Dict[str, Any]


def _json_safe(value: Any) -> Any:
    """Recursively convert numpy/pydantic values into plain JSON-safe Python types."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(item) for item in value]
    if hasattr(value, "model_dump"):
        return _json_safe(value.model_dump())
    if hasattr(value, "item"):
        try:
            return _json_safe(value.item())
        except Exception:
            pass
    if hasattr(value, "tolist"):
        try:
            return _json_safe(value.tolist())
        except Exception:
            pass
    return value


def _serialize_observation(observation: ExperimentObservation) -> Dict[str, Any]:
    """Serialize observations for HTTP while preserving metadata."""
    return _json_safe(
        {
            "observation": observation.model_dump(exclude={"reward", "done"}),
            "reward": observation.reward,
            "done": observation.done,
        }
    )


def _session_error(status_code: int, detail: str) -> HTTPException:
    return HTTPException(status_code=status_code, detail=detail)


app = create_app(
    BioExperimentEnvironment,
    ExperimentAction,
    ExperimentObservation,
    env_name="drylabsim",
    max_concurrent_envs=int(os.environ.get("MAX_ENVS", "4")),
)
app.state.sessions = {}
app.state.sessions_lock = asyncio.Lock()


def _prune_scaffold_routes() -> None:
    """Remove autogenerated routes we replace with session-backed HTTP control."""
    blocked_paths = {"/", "/reset", "/step", "/state"}
    app.router.routes[:] = [
        route
        for route in app.router.routes
        if getattr(route, "path", None) not in blocked_paths
    ]


async def _get_session(session_id: str) -> SessionRecord:
    async with app.state.sessions_lock:
        record = app.state.sessions.get(session_id)
    if record is None:
        raise _session_error(
            status.HTTP_404_NOT_FOUND,
            f"Unknown session_id: {session_id}",
        )
    return record


async def _close_all_sessions() -> None:
    async with app.state.sessions_lock:
        sessions = app.state.sessions
        app.state.sessions = {}
    for record in sessions.values():
        try:
            record.env.close()
        except Exception:
            pass


_prune_scaffold_routes()
register_demo_ui(app)


@app.on_event("shutdown")
async def shutdown_sessions() -> None:
    """Close any in-memory HTTP sessions on shutdown."""
    await _close_all_sessions()


@app.get("/", include_in_schema=False)
async def root_redirect() -> RedirectResponse:
    """Send the root page to the custom demo UI instead of OpenEnv's default UI."""
    return RedirectResponse(url="/demo", status_code=308)


@app.post(
    "/reset",
    tags=["Environment Control"],
    summary="Reset the environment with a session-backed episode",
)
async def reset(
    request: SessionResetRequest = Body(default_factory=SessionResetRequest),
) -> Dict[str, Any]:
    """Create a new HTTP session and return the initial observation."""
    env = BioExperimentEnvironment(
        domain_randomise=(
            request.domain_randomise if request.domain_randomise is not None else True
        ),
    )

    try:
        observation = env.reset(
            seed=request.seed,
            task_name=request.task_name,
            scenario_name=request.scenario_name,
        )
    except ValueError as exc:
        env.close()
        raise _session_error(status.HTTP_422_UNPROCESSABLE_ENTITY, str(exc)) from exc
    except Exception:
        env.close()
        raise

    session_id = str(uuid4())
    record = SessionRecord(env=env, lock=asyncio.Lock())
    async with app.state.sessions_lock:
        app.state.sessions[session_id] = record

    payload = _serialize_observation(observation)
    payload["session_id"] = session_id
    return payload


@app.post(
    "/step",
    tags=["Environment Control"],
    summary="Execute an action inside an existing HTTP session",
)
async def step(request: SessionStepRequest) -> Dict[str, Any]:
    """Mutate only the environment associated with the provided session_id."""
    record = await _get_session(request.session_id)

    try:
        action = ExperimentAction.model_validate(request.action)
    except ValidationError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=exc.errors(),
        ) from exc

    async with record.lock:
        observation = record.env.step(action)

    payload = _serialize_observation(observation)
    payload["session_id"] = request.session_id
    return payload


@app.get(
    "/state",
    tags=["State Management"],
    summary="Get state for an existing HTTP session",
)
async def state(session_id: Optional[str] = Query(default=None, min_length=1)) -> Dict[str, Any]:
    """Return state for the exact session that owns the latent trajectory."""
    if session_id is None:
        env = BioExperimentEnvironment()
        try:
            state_obj = env.state
            return _json_safe(
                state_obj.model_dump()
                if hasattr(state_obj, "model_dump")
                else dict(state_obj)
            )
        finally:
            env.close()

    record = await _get_session(session_id)
    async with record.lock:
        state_obj = record.env.state
        state_payload = _json_safe(
            state_obj.model_dump() if hasattr(state_obj, "model_dump") else dict(state_obj)
        )
    state_payload["session_id"] = session_id
    return state_payload


def main(host: str = "0.0.0.0", port: int = 8000):
    """Entry point for direct execution via uv run or python -m."""

    import argparse
    import uvicorn

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default=host)
    parser.add_argument("--port", type=int, default=None)
    args = parser.parse_args()

    resolved_port = args.port
    if resolved_port is None:
        resolved_port = int(os.environ.get("PORT", str(port)))
    uvicorn.run(app, host=args.host, port=resolved_port)


if __name__ == "__main__":
    main()
