"""FastAPI application for the DryLabSim environment."""

import os

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required for the web interface. Install dependencies with 'uv sync'"
    ) from e

from fastapi.responses import RedirectResponse

try:
    from ..models import ExperimentAction, ExperimentObservation
    from .demo_ui import register_demo_ui
    from .drylabsim_environment import BioExperimentEnvironment
except ImportError:  # pragma: no cover - direct module import path
    from models import ExperimentAction, ExperimentObservation
    from server.demo_ui import register_demo_ui
    from server.drylabsim_environment import BioExperimentEnvironment

app = create_app(
    BioExperimentEnvironment,
    ExperimentAction,
    ExperimentObservation,
    env_name="drylabsim",
    max_concurrent_envs=int(os.environ.get("MAX_ENVS", "4")),
)


def _prune_scaffold_root_route() -> None:
    """Remove OpenEnv's autogenerated root route so our redirect wins reliably."""
    app.router.routes[:] = [
        route for route in app.router.routes if getattr(route, "path", None) != "/"
    ]


_prune_scaffold_root_route()
register_demo_ui(app)


@app.get("/", include_in_schema=False)
async def root_redirect() -> RedirectResponse:
    """Send the root page to the custom demo UI instead of OpenEnv's default UI."""
    return RedirectResponse(url="/demo", status_code=308)


def main(host: str = "0.0.0.0", port: int = 8000):
    """Entry point for direct execution via uv run or python -m."""

    import argparse
    import uvicorn

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default=host)
    parser.add_argument("--port", type=int, default=None)
    args = parser.parse_args()

    resolved_port = args.port
    if resolved_port is None:
        resolved_port = int(os.environ.get("PORT", str(port)))
    uvicorn.run(app, host=args.host, port=resolved_port)


if __name__ == "__main__":
    main()
